version: '3.7'

services:
  gateway:
    build: ./gateway
    image: app/gateway
    container_name: gateway
    restart: always
    hostname: gateway
    volumes:
      - ./gateway/.env:/var/www/app/.env
    ports:
      - "3000:3000"
    networks:
      - backend

  auth:
    build: ./auth
    container_name: auth
    image: app/auth
    restart: always
    hostname: auth
    volumes:
      - ./auth/.env:/var/www/app/.env
    networks:
      - backend
    links:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
    networks:
      - backend

volumes:
  rabbitmq_data:
    name: rabbitmq_data
  rabbitmq_log:
    name: rabbitmq_log
  postgres_data:
    name: postgres_data

networks:
  backend:
    driver: bridge
